"""update[users]: добавил поля - create_at для отображения даты создания профиля и last_access для отображения даты последнего обращения

Revision ID: 42745496d524
Revises: 6252710f52f3
Create Date: 2023-06-27 19:09:29.785851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42745496d524'
down_revision = '6252710f52f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_access', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_access')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
