"""update[users]: Добавил новое поле - is_active, обновил размер поля password до 32 - текущий размер хэша

Revision ID: 6252710f52f3
Revises: b6bce5000a68
Create Date: 2023-06-27 17:03:40.284077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6252710f52f3'
down_revision = 'b6bce5000a68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
