"""update[users]: Добавил новые поля - is_superuser, is_staff

Revision ID: edb2b7b9eba0
Revises: 73ea1c883a81
Create Date: 2023-06-29 11:56:08.394247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb2b7b9eba0'
down_revision = '73ea1c883a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
